import { type NextPage } from "next";
import Head from "next/head";
import React, { useState } from "react";
import {handleTextChanged, handleKeyUp, toggleDone} from "./utils";

export interface ToDo {
  text: string;
  done: boolean;
  dateAdded: Date;
}

const Home: NextPage = () => {
  const [text, setText] = useState<string>("");
  const [items, setItems] = useState<ToDo[]>([]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen w-full bg-black">
        <div className="flex w-1/2 flex-col p-10">
          <input
            className="border-b-2 border-white bg-transparent px-4 text-3xl text-white focus:outline-0"
            type="text"
            value={text}
            onChange={handleTextChanged}
            onKeyUp={handleKeyUp}
          ></input>
          <ul className="text-xl text-white">
            {items.map((item, index) => {
              return (
                <li
                  className={
                    "flex flex-row justify-between border-b-2 border-white px-4 text-xl " +
                    (item.done ? "line-through" : "")
                  }
                  key={index}
                  id={index.toString()}
                  onClick={toggleDone}
                >
                  <span>{item.text}</span>
                </li>
              );
            })}
          </ul>
        </div>
      </main>
    </>
  );
};

export default Home;
